<?php
/**
 * sysPass
 *
 * @author    nuxsmin
 * @link      https://syspass.org
 * @copyright 2012-2018, Rubén Domínguez nuxsmin@$syspass.org
 *
 * This file is part of sysPass.
 *
 * sysPass is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * sysPass is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 *  along with sysPass.  If not, see <http://www.gnu.org/licenses/>.
 */

return [
    0 => __('Error while querying'),
    1 => __('There was an error'),
    2 => __('Session finished'),
    3 => __('Delete account?'),
    4 => __('Delete user?'),
    5 => __('You should save configuration in order to take effect'),
    6 => __('Generated Password'),
    7 => __('High level'),
    8 => __('Average level'),
    9 => __('Low level'),
    10 => __('Very High level'),
    11 => __('You should use at least 8 characters'),
    12 => __('Delete item?'),
    13 => __('Page not found'),
    14 => __('File not supported for preview'),
    15 => __('Delete file?'),
    16 => __('Your browser does not support HTML5 file uploads'),
    17 => __('Too many files'),
    18 => __('File size not allowed'),
    19 => __('MIME type not allowed'),
    20 => __('Clear the event log out?'),
    21 => __('Select Group'),
    22 => __('Select User'),
    23 => __('Select Profile'),
    24 => __('Select Client'),
    25 => __('Select Category'),
    26 => __('No results'),
    27 => __('Password options'),
    28 => __('Generate random password'),
    29 => __('Complexity'),
    30 => __('Reset'),
    31 => __('Password strength level'),
    32 => __('Show Password'),
    33 => __('Copy Username'),
    34 => __('Copy Password'),
    35 => __('Include Numbers'),
    36 => __('Include Uppercase'),
    37 => __('Include Symbols'),
    38 => __('Length'),
    39 => __('Select Action'),
    40 => __('YES'),
    41 => __('NO'),
    43 => __('Accept'),
    44 => __('Cancel'),
    45 => __('Password Copied into Clipboard'),
    46 => __('Error while copying to clipboard'),
    47 => __('Account Password'),
    48 => __('Send notifies?'),
    49 => __('Mark as Favorite'),
    50 => __('Delete Favorite'),
    51 => __('Clear Selection'),
    52 => __('Show Favorites'),
    53 => __('Display All'),
    54 => __('Help'),
    55 => __('No changes'),
    56 => __('Now'),
    57 => __('This process will import the detected LDAP users. Would you like to continue?'),
    58 => __('This action will reset all plugin data. Do you want to continue?'),
    59 => __('This process could take some time long. Do you wish to continue?'),
    60 => __('Warning'),
    61 => __('Session finished'),
    62 => __('Performing task. Please, do not close browser\'s window/tab.'),
    63 => __('Include Letters'),
    64 => __('Cookies disabled. Application won\'t work properly.'),
    65 => __('Clipboard not supported by your browser.'),
    66 => __('Performing auto-login'),
    67 => __('There is a more recent version of {0} plugin ({1})'),
    68 => __('Updated'),
    69 => __('Error while checking for updates'),
    70 => __('sysPass Notices'),
    71 => __('Clear the tracks out?'),
    72 => __('File downloaded')
];