<?php
// Generated on 1453548115
// This file is generated automatically on installation process
// Please, modify with caution, it could break the application
$CONFIG = array (
  'account_count' => 12,
  'account_link' => 1,
  'account_passtoimage' => false,
  'checknotices' => true,
  'checkupdates' => true,
  'config_hash' => '53489a9c67140c7a72d12b71cb1eefd5',
  'dbhost' => 'localhost',
  'dbname' => 'syspass',
  'dbpass' => 'ff6555bb87aa43d732346d2224736095',
  'dbuser' => 'sp_admin',
  'debug' => false,
  'demo_enabled' => false,
  'files_allowed_exts' => 'PDF,JPG,GIF,PNG,ODT,ODS,DOC,DOCX,XLS,XSL,VSD,TXT,CSV,BAK',
  'files_allowed_size' => 1024,
  'files_enabled' => true,
  'globalsearch' => false,
  'installed' => 1,
  'ldap_base' => '',
  'ldap_enabled' => false,
  'ldap_group' => '',
  'ldap_server' => '',
  'ldap_userattr' => '',
  'log_enabled' => true,
  'mail_enabled' => false,
  'mail_from' => '',
  'mail_server' => '',
  'passwordsalt' => 'b6417b24176faa7d6543dc05874ca6',
  'proxy_enabled' => false,
  'proxy_pass' => '',
  'proxy_port' => '',
  'proxy_server' => '',
  'proxy_user' => '',
  'resultsascards' => false,
  'session_timeout' => '300',
  'site_lang' => '',
  'sitetheme' => 'material-blue',
  'version' => '1316011001',
  'wiki_enabled' => false,
  'wiki_filter' => '',
  'wiki_pageurl' => '',
  'wiki_searchurl' => '',
);
