<!DOCTYPE html>
<html lang="es">
    <head>
        <title><?php echo $appInfo['appname'],' :: ',$appInfo['appdesc']; ?></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link rel="icon" TYPE="image/png" href="<?php echo $logo; ?>">
        <link rel="stylesheet" href="<?php echo $cssLink;?>" />
        <script type="text/javascript" src="<?php echo $jsLink?>"></script>
    </head>
