            </div> <!-- Close container -->
            <footer>
                <div id="updates"></div>
                <div id="project">
                    <a href="<?php echo $appInfo['appwebsite']; ?>" target="_blank" title="<?php echo  _('Ayuda :: FAQ :: Changelog'); ?>"><?php echo $appInfo['appname'], ' ', $appVersion; ?></a>
                    &nbsp;::&nbsp;
                    <a href="<?php echo $appInfo['appblog']; ?>" target="_blank" title="<?php echo _('Un proyecto de cygnux.org'); ?>" >cygnux.org</a>
                </div> <!-- Close Project -->
            </footer> <!-- Close footer -->
        <script>$('input[type="text"], select, textarea').placeholder().mouseenter(function(){ $(this).focus(); });</script>
        </div> <!-- Close wrap -->
    </body>
</html>