ALTER TABLE `customers` ADD `customer_isGlobal` BIT(1) DEFAULT b'0' NULL;
ALTER TABLE `usrData` ADD `user_ssoLogin` VARCHAR(100) NULL AFTER `user_login`;

DROP INDEX IDX_login ON `usrData`;
CREATE UNIQUE INDEX `IDX_login` ON `usrData` (`user_login`, `user_ssoLogin`);

ALTER TABLE plugins ADD `plugin_available` BIT(1) DEFAULT b'0' NULL;

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `actions` (
  `action_id` SMALLINT(5) UNSIGNED NOT NULL,
  `action_name` VARCHAR(50) NOT NULL,
  `action_text` VARCHAR(100) NOT NULL,
  `action_route` VARCHAR(100),
  PRIMARY KEY (`action_id`, `action_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

INSERT INTO actions VALUES (1, 'ACCOUNT_SEARCH', 'Buscar Cuentas', 'account/search');
INSERT INTO actions VALUES (10, 'ACCOUNT', 'Cuentas', 'account/index');
INSERT INTO actions VALUES (100, 'ACCOUNT_VIEW', 'Ver Cuenta', 'account/view');
INSERT INTO actions VALUES (101, 'ACCOUNT_CREATE', 'Nueva Cuenta', 'account/create');
INSERT INTO actions VALUES (102, 'ACCOUNT_EDIT', 'Editar Cuenta', 'account/edit');
INSERT INTO actions VALUES (103, 'ACCOUNT_DELETE', 'Eliminar Cuenta', 'account/delete');
INSERT INTO actions VALUES (104, 'ACCOUNT_VIEW_PASS', 'Ver Clave', 'account/viewPass');
INSERT INTO actions VALUES (105, 'ACCOUNT_VIEW_HISTORY', 'Ver Historial', 'account/viewHistory');
INSERT INTO actions VALUES (106, 'ACCOUNT_EDIT_PASS', 'Editar Clave de Cuenta', 'account/editPass');
INSERT INTO actions VALUES (107, 'ACCOUNT_EDIT_RESTORE', 'Restaurar Cuenta', 'account/restore');
INSERT INTO actions VALUES (108, 'ACCOUNT_COPY', 'Copiar Cuenta', 'account/copy');
INSERT INTO actions VALUES (109, 'ACCOUNT_COPY_PASS', 'Copiar Clave', 'account/copyPass');
INSERT INTO actions VALUES (11, 'ACCOUNT_FILE', 'Archivos', 'account/listFile');
INSERT INTO actions VALUES (111, 'ACCOUNT_FILE_VIEW', 'Ver Archivo', 'account/viewFile');
INSERT INTO actions VALUES (112, 'ACCOUNT_FILE_UPLOAD', 'Subir Archivo', 'account/uploadFile');
INSERT INTO actions VALUES (113, 'ACCOUNT_FILE_DOWNLOAD', 'Descargar Archivo', 'account/downloadFile');
INSERT INTO actions VALUES (114, 'ACCOUNT_FILE_DELETE', 'Eliminar Archivo', 'account/deleteFile');
INSERT INTO actions VALUES (12, 'ACCOUNT_REQUEST', 'Peticiones', 'account/request');
INSERT INTO actions VALUES (13, 'ACCOUNT_FAVORITE', 'Favoritos', 'favorite/index');
INSERT INTO actions VALUES (130, 'ACCOUNT_FAVORITE_VIEW', 'Ver Favoritos', 'favorite/view');
INSERT INTO actions VALUES (131, 'ACCOUNT_FAVORITE_ADD', 'Añadir Favorito', 'favorite/add');
INSERT INTO actions VALUES (133, 'ACCOUNT_FAVORITE_DELETE', 'Eliminar Favorito', 'favorite/delete');
INSERT INTO actions VALUES (20, 'WIKI', 'Wiki', 'wiki/index');
INSERT INTO actions VALUES (200, 'WIKI_VIEW', 'Ver Wiki', 'wiki/view');
INSERT INTO actions VALUES (201, 'WIKI_NEW', 'Añadir Wiki', 'wiki/create');
INSERT INTO actions VALUES (202, 'WIKI_EDIT', 'Editar Wiki', 'wiki/edit');
INSERT INTO actions VALUES (203, 'WIKI_DELETE', 'Eliminar Wiki', 'wiki/delete');
INSERT INTO actions VALUES (60, 'ITEMS_MANAGE', 'Elementos y Personalización', 'itemManager/index');
INSERT INTO actions VALUES (61, 'CATEGORY', 'Gestión Categorías', 'category/index');
INSERT INTO actions VALUES (610, 'CATEGORY_VIEW', 'Ver Categoría', 'category/view');
INSERT INTO actions VALUES (611, 'CATEGORY_CREATE', 'Nueva Categoría', 'category/create');
INSERT INTO actions VALUES (612, 'CATEGORY_EDIT', 'Editar Categoría', 'category/edit');
INSERT INTO actions VALUES (613, 'CATEGORY_DELETE', 'Eliminar Categoría', 'category/delete');
INSERT INTO actions VALUES (615, 'CATEGORY_SEARCH', 'Buscar Categoría', 'category/search');
INSERT INTO actions VALUES (62, 'CLIENT', 'Gestión Clientes', 'client/index');
INSERT INTO actions VALUES (620, 'CLIENT_VIEW', 'Ver Cliente', 'client/view');
INSERT INTO actions VALUES (621, 'CLIENT_CREATE', 'Nuevo CLiente', 'client/create');
INSERT INTO actions VALUES (622, 'CLIENT_EDIT', 'Editar Cliente', 'client/edit');
INSERT INTO actions VALUES (623, 'CLIENT_DELETE', 'Eliminar Cliente', 'client/delete');
INSERT INTO actions VALUES (625, 'CLIENT_SEARCH', 'Buscar Cliente', 'client/search');
INSERT INTO actions VALUES (63, 'APITOKEN', 'Gestión Autorizaciones API', 'apiToken/index');
INSERT INTO actions VALUES (630, 'APITOKEN_CREATE', 'Nuevo Token API', 'apiToken/create');
INSERT INTO actions VALUES (631, 'APITOKEN_VIEW', 'Ver Token API', 'apiToken/view');
INSERT INTO actions VALUES (632, 'APITOKEN_EDIT', 'Editar Token API', 'apiToken/edit');
INSERT INTO actions VALUES (633, 'APITOKEN_DELETE', 'Eliminar Token API', 'apiToken/delete');
INSERT INTO actions VALUES (635, 'APITOKEN_SEARCH', 'Buscar Token API', 'apiToken/search');
INSERT INTO actions VALUES (64, 'CUSTOMFIELD', 'Gestión Campos Personalizados', 'customField/index');
INSERT INTO actions VALUES (640, 'CUSTOMFIELD_CREATE', 'Nuevo Campo Personalizado', 'customField/create');
INSERT INTO actions VALUES (641, 'CUSTOMFIELD_VIEW', 'Ver Campo Personalizado', 'customField/view');
INSERT INTO actions VALUES (642, 'CUSTOMFIELD_EDIT', 'Editar Campo Personalizado', 'customField/edit');
INSERT INTO actions VALUES (643, 'CUSTOMFIELD_DELETE', 'Eliminar Campo Personalizado', 'customField/delete');
INSERT INTO actions VALUES (645, 'CUSTOMFIELD_SEARCH', 'Buscar Campo Personalizado', 'customField/search');
INSERT INTO actions VALUES (65, 'PUBLICLINK', 'Enlaces Públicos', 'publicLink/index');
INSERT INTO actions VALUES (650, 'PUBLICLINK_CREATE', 'Crear Enlace Público', 'publicLink/create');
INSERT INTO actions VALUES (651, 'PUBLICLINK_VIEW', 'Ver Enlace Público', 'publicLink/view');
INSERT INTO actions VALUES (653, 'PUBLICLINK_DELETE', 'Eliminar Enlace Público', 'publicLink/delete');
INSERT INTO actions VALUES (654, 'PUBLICLINK_REFRESH', 'Actualizar Enlace Público', 'publicLink/refresh');
INSERT INTO actions VALUES (655, 'PUBLICLINK_SEARCH', 'Buscar Enlace Público', 'publicLink/search');
INSERT INTO actions VALUES (66, 'FILE', 'Gestión de Archivos', 'file/index');
INSERT INTO actions VALUES (661, 'FILE_VIEW', 'Ver Archivo', 'file/view');
INSERT INTO actions VALUES (663, 'FILE_DELETE', 'Eliminar Archivo', 'file/delete');
INSERT INTO actions VALUES (665, 'FILE_SEARCH', 'Buscar Archivo', 'file/search');
INSERT INTO actions VALUES (67, 'ACCOUNTMGR', 'Gestión de Cuentas', 'accountManager/index');
INSERT INTO actions VALUES (6701, 'ACCOUNTMGR_HISTORY', 'Gestión de Cuenta (H)', 'accountHistoryManager/index');
INSERT INTO actions VALUES (671, 'ACCOUNTMGR_VIEW', 'Ver Cuenta', 'accountManager/view');
INSERT INTO actions VALUES (673, 'ACCOUNTMGR_DELETE', 'Eliminar Cuenta', 'accountManager/delete');
INSERT INTO actions VALUES (6731, 'ACCOUNTMGR_DELETE_HISTORY', 'Eliminar Cuenta', 'accountHistoryManager/delete');
INSERT INTO actions VALUES (675, 'ACCOUNTMGR_SEARCH', 'Buscar Cuenta', 'accountManager/search');
INSERT INTO actions VALUES (6751, 'ACCOUNTMGR_SEARCH_HISTORY', 'Buscar Cuenta', 'accountHistoryManager/search');
INSERT INTO actions VALUES (6771, 'ACCOUNTMGR_RESTORE', 'Restaurar Cuenta', 'accountManager/restore');
INSERT INTO actions VALUES (68, 'TAG', 'Gestión de Etiquetas', 'tag/index');
INSERT INTO actions VALUES (680, 'TAG_CREATE', 'Nueva Etiqueta', 'tag/create');
INSERT INTO actions VALUES (681, 'TAG_VIEW', 'Ver Etiqueta', 'tag/view');
INSERT INTO actions VALUES (682, 'TAG_EDIT', 'Editar Etiqueta', 'tag/edit');
INSERT INTO actions VALUES (683, 'TAG_DELETE', 'Eliminar Etiqueta', 'tag/delete');
INSERT INTO actions VALUES (685, 'TAG_SEARCH', 'Buscar Etiqueta', 'tag/search');
INSERT INTO actions VALUES (69, 'PLUGIN', 'Gestión Plugins', 'plugin/index');
INSERT INTO actions VALUES (690, 'PLUGIN_NEW', 'Nuevo Plugin', 'plugin/create');
INSERT INTO actions VALUES (691, 'PLUGIN_VIEW', 'Ver Plugin', 'plugin/view');
INSERT INTO actions VALUES (695, 'PLUGIN_SEARCH', 'Buscar Plugin', 'plugin/search');
INSERT INTO actions VALUES (696, 'PLUGIN_ENABLE', 'Habilitar Plugin', 'plugin/enable');
INSERT INTO actions VALUES (697, 'PLUGIN_DISABLE', 'Deshabilitar Plugin', 'plugin/disable');
INSERT INTO actions VALUES (698, 'PLUGIN_RESET', 'Restablecer Plugin', 'plugin/reset');
INSERT INTO actions VALUES (70, 'ACCESS_MANAGE', 'Usuarios y Accesos', 'accessManager/index');
INSERT INTO actions VALUES (71, 'USER', 'Gestión Usuarios', 'user/index');
INSERT INTO actions VALUES (710, 'USER_VIEW', 'Ver Usuario', 'user/view');
INSERT INTO actions VALUES (711, 'USER_CREATE', 'Nuevo Usuario', 'user/create');
INSERT INTO actions VALUES (712, 'USER_EDIT', 'Editar Usuario', 'user/edit');
INSERT INTO actions VALUES (713, 'USER_DELETE', 'Eliminar Usuario', 'user/delete');
INSERT INTO actions VALUES (714, 'USER_EDIT_PASS', 'Editar Clave Usuario', 'user/editPass');
INSERT INTO actions VALUES (715, 'USER_SEARCH', 'Buscar Usuario', 'user/search');
INSERT INTO actions VALUES (72, 'GROUP', 'Gestión Grupos', 'group/index');
INSERT INTO actions VALUES (720, 'GROUP_VIEW', 'Ver Grupo', 'group/view');
INSERT INTO actions VALUES (721, 'GROUP_CREATE', 'Nuevo Grupo', 'group/create');
INSERT INTO actions VALUES (722, 'GROUP_EDIT', 'Editar Grupo', 'group/edit');
INSERT INTO actions VALUES (723, 'GROUP_DELETE', 'Eliminar Grupo', 'group/delete');
INSERT INTO actions VALUES (725, 'GROUP_SEARCH', 'Buscar Grupo', 'group/search');
INSERT INTO actions VALUES (73, 'PROFILE', 'Gestión Perfiles', 'profile/index');
INSERT INTO actions VALUES (730, 'PROFILE_VIEW', 'Ver Perfil', 'profile/view');
INSERT INTO actions VALUES (731, 'PROFILE_CREATE', 'Nuevo Perfil', 'profile/create');
INSERT INTO actions VALUES (732, 'PROFILE_EDIT', 'Editar Perfil', 'profile/edit');
INSERT INTO actions VALUES (733, 'PROFILE_DELETE', 'Eliminar Perfil', 'profile/delete');
INSERT INTO actions VALUES (735, 'PROFILE_SEARCH', 'Buscar Perfil', 'profile/search');
INSERT INTO actions VALUES (740, 'PREFERENCE', 'Gestión Preferencias', 'preference/index');
INSERT INTO actions VALUES (741, 'PREFERENCE_GENERAL', 'Preferencias General', 'preference/general');
INSERT INTO actions VALUES (742, 'PREFERENCE_SECURITY', 'Preferencias Seguridad', 'preference/security');
INSERT INTO actions VALUES (760, 'NOTICE', 'Notificaciones', 'notice/index');
INSERT INTO actions VALUES (761, 'NOTICE_USER', 'Notificaciones Usuario', 'noticeUser/index');
INSERT INTO actions VALUES (7610, 'NOTICE_USER_VIEW', 'Ver Notificación', 'noticeUser/view');
INSERT INTO actions VALUES (7611, 'NOTICE_USER_CREATE', 'Crear Notificación', 'noticeUser/create');
INSERT INTO actions VALUES (7612, 'NOTICE_USER_EDIT', 'Editar Notificación', 'noticeUser/edit');
INSERT INTO actions VALUES (7613, 'NOTICE_USER_DELETE', 'Eliminar Notificación', 'noticeUser/delete');
INSERT INTO actions VALUES (7614, 'NOTICE_USER_CHECK', 'Marcar Notificación', 'noticeUser/check');
INSERT INTO actions VALUES (7615, 'NOTICE_USER_SEARCH', 'Buscar Notificación', 'noticeUser/search');
INSERT INTO actions VALUES (1000, 'CONFIG', 'Configuración', 'config/index');
INSERT INTO actions VALUES (1001, 'CONFIG_GENERAL', 'Configuración General', 'config/general');
INSERT INTO actions VALUES (1010, 'ACCOUNT_CONFIG', 'Configuración Cuentas', 'account/config');
INSERT INTO actions VALUES (1020, 'WIKI_CONFIG', 'Configuración Wiki', 'wiki/config');
INSERT INTO actions VALUES (1030, 'ENCRYPTION_CONFIG', 'Configuración Encriptación', 'encryption/config');
INSERT INTO actions VALUES (1031, 'ENCRYPTION_REFRESH', 'Actualizar Hash', 'encryption/updateHash');
INSERT INTO actions VALUES (1032, 'ENCRYPTION_TEMPPASS', 'Clave Maestra Temporal', 'encryption/createTempPass');
INSERT INTO actions VALUES (1040, 'BACKUP_CONFIG', 'Configuración Copia de Seguridad', 'backup/config');
INSERT INTO actions VALUES (1050, 'IMPORT_CONFIG', 'Configuración Importación', 'import/config');
INSERT INTO actions VALUES (1051, 'IMPORT_CSV', 'Importar CSV', 'import/csv');
INSERT INTO actions VALUES (1052, 'IMPORT_XML', 'Importar XML', 'import/xml');
INSERT INTO actions VALUES (1060, 'EXPORT_CONFIG', 'Configuración Exportación', 'export/config');
INSERT INTO actions VALUES (1061, 'EXPORT_XML', 'Exportar XML', 'export/xml');
INSERT INTO actions VALUES (1070, 'MAIL_CONFIG', 'Configuración Email', 'mail/config');
INSERT INTO actions VALUES (1080, 'LDAP_CONFIG', 'Configuración LDAP', 'ldap/config');
INSERT INTO actions VALUES (1081, 'LDAP_SYNC', 'Sincronización LDAP', 'ldap/sync');
INSERT INTO actions VALUES (90, 'EVENTLOG', 'Registro de Eventos', 'eventlog/index');